from __future__ import annotations

from slimder_man.config.defaults import tiny_default_config


def build_config_yaml(project_name: str = "tiny_moe_cpu_smoke", paper_faithful: bool = True, quantization: bool = False) -> str:
    import yaml

    cfg = tiny_default_config()
    cfg.project.name = project_name
    cfg.project.paper_faithful = paper_faithful
    cfg.quantization.enabled = quantization
    return yaml.safe_dump(cfg.model_dump(mode="json"), sort_keys=False)


def create_app(test_mode: bool = False):
    try:
        import gradio as gr
    except Exception:
        if test_mode:
            return {"test_mode": True, "yaml": build_config_yaml()}
        raise
    import subprocess
    import sys
    import tempfile
    from pathlib import Path

    def _run_generated(yaml_text: str, command: str) -> str:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "config.yaml"
            path.write_text(yaml_text, encoding="utf-8")
            proc = subprocess.run([sys.executable, "-m", "slimder_man.cli", command, str(path), "--json"], text=True, capture_output=True)
            return proc.stdout if proc.returncode == 0 else proc.stderr

    with gr.Blocks(title="Slimder Man") as demo:
        gr.Markdown("# Slimder Man")
        with gr.Tabs():
            with gr.Tab("Project"):
                project = gr.Textbox(value="tiny_moe_cpu_smoke", label="Project name")
                faithful = gr.Checkbox(value=True, label="Paper faithful")
                quant = gr.Checkbox(value=False, label="Augmented quantization", interactive=False)
            with gr.Tab("Teacher & Dataset"):
                gr.Textbox(value="tiny", label="Model ID or path")
                gr.Dropdown(["synthetic", "hf_dataset", "jsonl", "parquet", "text", "tokenized"], value="synthetic", label="Dataset type")
            with gr.Tab("Analyze"):
                analyze_btn = gr.Button("Run Analyze")
                analyze_out = gr.Code(language="json", label="Analyze Output")
            with gr.Tab("Recommendations"):
                gr.Markdown("Preset recommendations are generated by the CLI and run pipeline.")
            with gr.Tab("Compression"):
                gr.Markdown("Compression runs as part of `slimder run` for the tiny smoke workflow.")
            with gr.Tab("Training / Distillation"):
                gr.Markdown("Training logs are written to `training_report.md`.")
            with gr.Tab("Evaluation"):
                gr.Markdown("Perplexity summaries are written to `run_summary.json`.")
            with gr.Tab("Artifacts"):
                gr.Markdown("Checkpoints, manifests, reports, and hashes are written under `project.output_dir`.")
            output = gr.Code(label="Generated YAML", language="yaml")
            btn = gr.Button("Generate Config")
            run_btn = gr.Button("Run Tiny Pipeline")
            run_out = gr.Code(language="json", label="Run Output")
        btn.click(build_config_yaml, inputs=[project, faithful, quant], outputs=[output])
        analyze_btn.click(lambda y: _run_generated(y, "analyze"), inputs=[output], outputs=[analyze_out])
        run_btn.click(lambda y: _run_generated(y, "run"), inputs=[output], outputs=[run_out])
    return demo
